name: Test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
defaults:
  run:
    working-directory: ./
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.7.0
          run_install: |
            # - recursive: true
            # args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - name: Setup environment variables
        run: |
           "NEXT_PUBLIC_FB_API_KEY=${{ secrets.NEXT_PUBLIC_FB_API_KEY }}" >> $GITHUB_ENV
           "NEXT_PUBLIC_API_KEY=${{ secrets.NEXT_PUBLIC_API_KEY }}" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          pnpm install
          pnpm build

      - name: Run Jest tests
        run: pnpm test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}